# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUI-MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUI-MVVM
pod 'Alamofire'
end
